Create Npc Update
BryceCanyonCounty/bcc-medical pull request #13
Opened 2024-09-19 13:33 UTC by EnerGonix

Npc now pickup player from the ground

2024-09-19 21:24 UTC, JusCampin commented
No files/code included in PR.

2024-09-20 01:56 UTC, AndrewR3K requested changes
You did not upload anything other than a file named "Npc Update" please remove this file and upload your changes if you wish to have them updated into our script. 

Thank you for your efforts and time!!

2024-09-20 01:56 UTC, AndrewR3K commented on Npc Update
> +Npc now pickup player from the ground
This file is not needed.

2024-09-20 12:52 UTC, EnerGonix commented on Npc Update
> +Npc now pickup player from the ground
im new to github sry

2024-09-20 12:53 UTC, closed without merging